### ISSUE TITLE
Rule error during analysis

### ISSUE THREAD

**Issue by olsh** [SonarSource/SonarTS#267]
After upgrading to 1.1 I get many errors with the following stack trace:

```
2017-11-01T14:37:51.5399817Z ##[error]ERROR: Rule error during analysis of : F:/TFS/Agentv2/_work/2/s/src/My.Project/angularApp/app/about/components/about.component.ts TypeError: this.getTypeChecker(...).getBaseTypeOfLiteralType is not a function
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at Walker.typeToString (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint-sonarts\lib\rules\noIgnoredReturnRule.js:226:48)
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at Walker.methodWithNoSideEffect (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint-sonarts\lib\rules\noIgnoredReturnRule.js:218:35)
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at Walker.visitCallExpression (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint-sonarts\lib\rules\noIgnoredReturnRule.js:210:22)
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at Walker.SyntaxWalker.visitNode (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\language\walker\syntaxWalker.js:302:22)
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:63
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at visitNode (F:\TFS\Agentv2\_work\2\s\src\My.Project\node_modules\typescript\lib\typescript.js:13876:20)
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at Object.forEachChild (F:\TFS\Agentv2\_work\2\s\src\My.Project\node_modules\typescript\lib\typescript.js:14068:24)
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at Walker.SyntaxWalker.walkChildren (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\language\walker\syntaxWalker.js:529:12)
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at Walker.SyntaxWalker.visitExpressionStatement (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\language\walker\syntaxWalker.js:108:14)
2017-11-01T14:37:51.5399817Z ##[error]ERROR:     at Walker.SyntaxWalker.visitNode (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\language\walker\syntaxWalker.js:356:22)
```

But the analysis completes despite the errors.

SonarTS 1.1 (build 1079)
SonarQube 6.6
TypeScript 2.1.6

Thank you!

**Comment by vilchik-elena** [comment]
@olsh Thanks a lot for reporting! Do you think you can provide single file reproducing this problem?
It is not obvious how `this.getTypeChecker(...).getBaseTypeOfLiteralType` could be `undefined`

**Comment by olsh** [comment]
Hi @vilchik-elena, please see the attached file.
[about.component.zip](https://github.com/SonarSource/SonarTS/files/1437472/about.component.zip)

**Comment by stas-vilchik** [comment]
I believe that the problem is in used typescript version (2.1.6). We [support](https://github.com/SonarSource/SonarTS/blob/master/sonarts-core/package.json#L37) typescript from version 2.2. We should improve our docs regarding this point.

**Comment by olsh** [comment]
Thanks, @stas-vilchik! 
I'll let you know if upgrading to 2.2 resolves the issue.

**Comment by olsh** [comment]
After upgrading to 2.2.2 I get the following error on the file (and some others):
```
2017-11-06T07:57:38.7261140Z ##[error]ERROR: Rule error during analysis of : F:/TFS/Agentv2/_work/2/s/src/My.Project/angularApp/app/about/about.module.ts TypeError: symbol.getJsDocTags is not a function
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at getDeprecation (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\rules\deprecationRule.js:109:38)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at cb (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\rules\deprecationRule.js:55:35)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at visitNode (F:\TFS\Agentv2\_work\2\s\src\My.Project\node_modules\typescript\lib\typescript.js:14197:20)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at Object.forEachChild (F:\TFS\Agentv2\_work\2\s\src\My.Project\node_modules\typescript\lib\typescript.js:14509:21)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at cb (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\rules\deprecationRule.js:62:23)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at visitEachNode (F:\TFS\Agentv2\_work\2\s\src\My.Project\node_modules\typescript\lib\typescript.js:14209:30)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at Object.forEachChild (F:\TFS\Agentv2\_work\2\s\src\My.Project\node_modules\typescript\lib\typescript.js:14500:24)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at cb (F:\TFS\Agentv2\_work\2\.sonarqube\out\.sonar\mod57\sonarts-bundle\node_modules\tslint\lib\rules\deprecationRule.js:62:23)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at visitNode (F:\TFS\Agentv2\_work\2\s\src\My.Project\node_modules\typescript\lib\typescript.js:14197:20)
2017-11-06T07:57:38.7261140Z ##[error]ERROR:     at Object.forEachChild (F:\TFS\Agentv2\_work\2\s\src\My.Project\node_modules\typescript\lib\typescript.js:14493:21)
```

**Comment by stas-vilchik** [comment]
Hi @olsh,

There is a bug in the `deprecation` tslint rule. We'll update our bundled tslint to fix the problem (#275). Meanwhile you can try to disable this rule, and run the analysis.

Thanks!
